# Generated by Django 4.2.1 on 2023-05-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_followmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followmodel',
            name='follower',
        ),
    ]
